env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: standard
overrides: []
parserOptions:
  ecmaVersion: latest
ignorePatterns: ['mongo-init.js', '**.**.spec.js']
rules:
  space-before-function-paren:
    ['error', { anonymous: 'always', named: 'never', asyncArrow: 'always' }]
  curly: ['error', 'multi']
  semi: ['error', 'always']
  no-unused-vars: 'warn'
