version: '3.1'
services:
  bj-mariadb:
    image: mariadb:10.9
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=example
      - MARIADB_DATABASE=battle_judge
    ports:
      - 3306:3306
    volumes:
      - ./db/scripts/maria-init.sql:/docker-entrypoint-initdb.d/maria-init.sql:ro
  bj-mongodb:
    image: mongo:6.0.3
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=example
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27017:27017
    volumes:
      - ./db/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - bj-mariadb
      - bj-mongodb